#---------------------------
# Global
#---------------------------

favicon: https://gleidson.me/favicon.ico
apple_touch_icon: https://gleidson.me/favicon.ico

tab_title_separator: " - "
force_https: true

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"

    highlightjs:
      style: "Github Gist"
      bg_color: true

    prismjs:
      style: "default"
      preprocess: true


fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false

  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right
    visible: hover
    icon: ""

  progressbar:
    enable: true
    height_px: 2
    color: "#c438ef"
    options: { showSpinner: false, trickleSpeed: 100 }

dark_mode:
  enable: false
  default: dark
  
color:
  body_bg_color: "#1e1b44"
  body_bg_color_dark: "#1e1b44"

  navbar_bg_color: "#1e1b44"
  navbar_bg_color_dark: "#1f3144"

  navbar_text_color: "#e8e8ec"
  navbar_text_color_dark: "#d0d0d0"

  text_color: "#c4c6c9"
  text_color_dark: "#c4c6c9"

  sec_text_color: "#a7a9ad"
  sec_text_color_dark: "#a7a9ad"

  post_text_color: "#c4c6c9"
  post_text_color_dark: "#c4c6c9"

  post_heading_color: "#c4c6c9"
  post_heading_color_dark: "#c4c6c9"

  post_link_color: "#1589e9"
  post_link_color_dark: "#1589e9"

  link_hover_color: "#53b9ea"
  link_hover_color_dark: "#30a9de"

  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"

  board_color: "#22272e"
  board_color_dark: "#252d38"

  scrollbar_color: "#c4c6c9"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"

font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%

custom_js:
custom_css: '/css/custom-css.css'
custom_head: ''
custom_html: ''

web_analytics: 
  enable: false
  baidu:
  google:

  gtag:
  tencent:
    sid:
    cid:
  woyaola: 
  cnzz:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false

lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css

#---------------------------
# Header
#---------------------------

navbar:
  blog_title: "Gleidson's Notes"
  ground_glass:
    enable: true
    px: 10
    alpha: 1.0
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "about", link: "https://gleidson.me", icon: "iconfont icon-user-fill" }

banner:
  parallax: true
  width_height_ratio: 0.5

scroll_down_arrow:
  enable: true
  banner_height_limit: 20
  scroll_after_turning_page: true

footer:
  content: '
   Feito com <i class="iconfont icon-love"></i> por Gleidson
  '


#---------------------------
# Home Page
#---------------------------
index:
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 30
  banner_mask_alpha: 0.0

  slogan:
    enable: true 
    text: "Notes' Home"
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []
  auto_excerpt:
    enable: true

  post_url_target: _self

  post_meta:
    date: false
    category: true
    tag: true

  post_sticky:
    enable: true
    icon: "iconfont icon-top"

#---------------------------
# Post Page
#---------------------------
post:
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.7

  default_index_img:

  meta:
    author:
      enable: false
    date:
      enable: true
      format: "DD/MM/YYYY"

    wordcount:
      enable: true
      format: "{} caracteres"
    min2read:
      enable: true
      format: "Aprox. {} min."
      awl: 2
      wpm: 160

    views:
      enable: false
      source: "busuanzi"
      format: "{} 次"

  updated:
    enable: false

    # Descriptive text before date
    content: 'Este artigo foi atualizado pela última vez em: '
    relative: false

  # Table of contents (TOC)
  toc:
    enable: true
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0

  copyright:
    enable: false
    content: 'Todos os artigos deste blog estão sob o contrato <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-SA 4.0 </a>, indique a fonte ao reimprimir！'

  prev_next:
    enable: true

  custom:
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">'

  image_zoom:
    enable: true
    img_url_replace: ['', '']

  footnote:
    enable: true
    header: ''

  math:
    enable: false
    specific: false
    engine: mathjax

  mermaid:
    enable: true
    specific: false
    # See: http://mermaid-js.github.io/mermaid/
    options: { theme: 'default' }

  comments:
    enable: true
    type: disqus

disqus:
  shortname: notes-gleidson-me
  disqusjs: false
  apikey:


#---------------------------
# Archive Page
#---------------------------
archive:
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3
  subtitle:


#---------------------------
# Category Page
#---------------------------
category:
  enable: true
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3
  subtitle:
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10


#---------------------------
# Tag Page
#---------------------------
tag:
  enable: false
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3
  subtitle:
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# About Page
#---------------------------
about:
  enable: false
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3
  subtitle:
  avatar: /img/avatar.png
  name: "Fluid"
  intro: "An elegant theme for Hexo"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }


#---------------------------
# Custom Page
#---------------------------
page:
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3
  subtitle: "Page not found"


#---------------------------
# Links Page
#---------------------------
links:
  enable: false
  banner_img: https://gleidson.me/assets/images/background.png
  banner_img_height: 40
  banner_mask_alpha: 0.3
  subtitle:
  items:

  onerror_avatar: /img/avatar.png

  custom:
    enable: false
    content: ''
  comments:
    enable: false
    type: disqus
